var a = 10;
var b = 20;
console.log(a == b);
console.log(a == 10);
// console.log(10=='10'); 
var c = 10;
var d = 20;
console.log(d === c);
console.log(c === 10);
// console.log(10==='10'); 
var e = 10;
var f = 20;
console.log(e != f);
console.log(e != 10);
// console.log(10!='10'); 
var g = 10;
var h = 20;
console.log(g !== h);
console.log(g !== 10);
// console.log(10!=='10'); 
var i = 30;
var j = 20;
console.log(i > j);
console.log(i > 30);
var k = 20;
var l = 20;
console.log(k >= l);
console.log(k >= 30);
var m = 10;
var n = 20;
console.log(m < n);
console.log(m < 10);
var x = 10;
var y = 20;
console.log(x <= y);
console.log(x <= 10);
