var a = false;
var b = true;
console.log(a && b);
console.log(b && true);
console.log(b && 10);
console.log(a && '10');
var a2 = false;
var b2 = true;
console.log(a2 || b2);
console.log(b2 || true);
console.log(b2 || 10);
console.log(a2 || '10');
var a3 = 20;
var b3 = 30;
console.log(!true);
console.log(!false);
console.log(!a3);
console.log(!b3);
console.log(!null);
